<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <!-- https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#copylocallockfileassemblies -->
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CK.AppIdentity.Hosting" Version="0.14.1" />
    <PackageReference Include="CK.AspNet" Version="21.0.1" />
    <PackageReference Include="CK.DB.AspNet.Auth" Version="31.0.2" />
    <PackageReference Include="CK.DB.User.NamedUser" Version="28.0.2" />
    <PackageReference Include="CK.DB.User.PreferredCulture" Version="0.4.3--ci.3" />
    <PackageReference Include="CK.DB.User.UserPassword" Version="28.0.2" />
    <PackageReference Include="CK.Cris.TypeScript" Version="0.55.2" />
    <PackageReference Include="CK.Ng.AspNet.Auth" Version="0.31.2" />
    <PackageReference Include="CK.TS.Angular" Version="0.31.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\CK.Ng.Zorro.BackOffice\CK.Ng.Zorro.BackOffice.csproj" />
  </ItemGroup>
</Project>