<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CK.Testing.NUnit" Version="14.1.0" />
        <PackageReference Include="CK.Testing.TypeScriptEngine" Version="0.28.0" />
        <PackageReference Include="CK.TS.Angular.Engine" Version="0.28.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
        <PackageReference Include="NUnit3TestAdapter" Version="5.1.0" />
        <PackageReference Include="NUnit.Analyzers" Version="4.10.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\..\CK.Ng.Zorro.DevKit\CK.Ng.Zorro.DevKit.csproj" />
    </ItemGroup>

</Project>
